# Generated by Django 3.2.7 on 2021-09-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_x', models.IntegerField()),
                ('grid_y', models.IntegerField()),
                ('plant', models.IntegerField()),
            ],
        ),
    ]
