# Generated by Django 3.2.7 on 2021-09-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitygarden', '0002_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
