# Generated by Django 3.2.7 on 2021-09-17 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitygarden', '0003_alter_connection_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='water_level',
            field=models.SmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
